import cv2
from PIL import Image
'''AT 30 FPS ->

 so we have generated a video of 12sec at 30 fps so it will 
roughly have 360 frames and at every 30 frame interval we are 
taking the frame then roughly in output we will have 360/30 = 12 frames(taken from video)

30 sec video ----> 900 frames in video
Extracted at 30 interval ---> 900/30 -->30 frames extracted

In case of test.webm (video generated by VARAD Bhai): 15 FPS
fps = total frames /duration

fps = 450/30 = 15 FPS ka video tha

to fir 

total frames = 15 x 30 = 450frames

Extracted frames at interval 30 = 450/30 = 15
'''

MAX_DIMENSION = 1024  # cap the longest side to this many pixels

def resize_for_vlm(pil_image, max_dim=MAX_DIMENSION):
    width, height = pil_image.size
    if max(width, height) <= max_dim:
        return pil_image  # already small enough, no change needed

    if width > height:
        new_width = max_dim
        new_height = int(height * (max_dim / width))
    else:
        new_height = max_dim
        new_width = int(width * (max_dim / height))

    return pil_image.resize((new_width, new_height), Image.LANCZOS)


def extract_frames(video_path, interval):
    cap = cv2.VideoCapture(video_path) # opens a video file so you can read frames from it
    extracted_frames = []
    frame_number = 0

    while True:
        success = cap.grab() # Grabs the raw frame in the video without decoding it,rreturn true/false but does not give actual frame
        if not success: # break when video is endedd as grab not able to take frame so returns false
            break

        if frame_number % interval == 0: 
            ret, frame = cap.retrieve() #ret ->shows wheather the decoding is successfull or not, frame -> stores numpy array of the image
            if not ret:
                break
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) # converts the standard opencv format from BGR to RGB
            pil_image = Image.fromarray(frame_rgb) # converts an numpy array into PIL image object which is used by most VLM libraries like qwen instead of raw array
            pil_image = resize_for_vlm(pil_image)
            
            extracted_frames.append({
                "frame_number": frame_number, # position of the frame
                "rgb_image": frame_rgb, # the raw array in RGB format
                "pil_image": pil_image, # PIL-wrapped version of the same frame, ready to hand directly to VLM
            })

        frame_number += 1

    cap.release() # now we are not accessing the video, we have released the jutsu
    return extracted_frames


if __name__ == "__main__":
    import sys
    path = sys.argv[1]
    interval = 30

    frames = extract_frames(path, interval)
    print(f"Extracted {len(frames)} frames")
    print(f"First frame number: {frames[0]['frame_number']}")

