import cv2
from PIL import Image
'''AT 30 FPS ->

 so we have generated a video of 12sec at 30 fps so it will 
roughly have 360 frames and at every 30 frame interval we are 
taking the frame then roughly in output we will have 360/30 = 12 frames(taken from video)

30 sec video ----> 900 frames in video
Extracted at 30 interval ---> 900/30 -->30 frames extracted

In case of test.webm (video generated by VARAD Bhai): 15 FPS
fps = total frames /duration

fps = 450/30 = 15 FPS ka video tha

to fir 

total frames = 15 x 30 = 450frames

Extracted frames at interval 30 = 450/30 = 15
'''
def extract_frames(video_path, interval):
    cap = cv2.VideoCapture(video_path)
    extracted_frames = []
    frame_number = 0

    while True:
        success = cap.grab()
        if not success:
            break

        if frame_number % interval == 0:
            ret, frame = cap.retrieve()
            if not ret:
                break
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            pil_image = Image.fromarray(frame_rgb)

            extracted_frames.append({
                "frame_number": frame_number,
                "rgb_image": frame_rgb,
                "pil_image": pil_image,
            })

        frame_number += 1

    cap.release()
    return extracted_frames


if __name__ == "__main__":
    import sys
    path = sys.argv[1]
    interval = 30

    frames = extract_frames(path, interval)
    print(f"Extracted {len(frames)} frames")
    print(f"First frame number: {frames[0]['frame_number']}")

